schemaVersion: treeseed.platform-host-template/v1
id: capacity-provider
profiles: [capacity-provider]
integration: { id: development, digest: 'sha256:65128b716bd37cb86c8599d1938b17db4376ad95b31b1069e3783d0164dbf942' }
inputs:
  - { name: controlPlaneUrl, required: true, sensitive: false }
  - { name: teamRegistrationCode, required: true, sensitive: true }
